CREATE TABLE tracker (
    id INT AUTO_INCREMENT PRIMARY KEY,
    token VARCHAR(255) NOT NULL,
    ip VARCHAR(45) NOT NULL,
    latitud VARCHAR(50) NOT NULL,
    longitud VARCHAR(50) NOT NULL,
    pais VARCHAR(100) NOT NULL,
    navegador VARCHAR(255) NOT NULL,
    sistema VARCHAR(255) NOT NULL,
    add_date DATETIME DEFAULT CURRENT_TIMESTAMP
);